/*
 ******************************************************************************
 File:     main.cpp
 Info:     Generated by Atollic TrueSTUDIO(R) 7.1.0   2017-03-19

 The MIT License (MIT)
 Copyright (c) 2009-2017 Atollic AB

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.

 ******************************************************************************
 */

/* Includes */
#include <ARSystemTimer.h>
#include "stm32f4xx.h"
#include "Memory.h"
#include "TestsPreReqs.h"
#include <stdlib.h>

#include "stm32f4xx_it.h"
#include "TestGroups.h"
#include <ARModuleManager.h>
#include <ARTimer.h>

using namespace AutoRobo;

//ADD_TEST_GROUP(MemoryTestGroup);
//ADD_TEST_GROUP(MathTestGroup);
ADD_TEST_GROUP(TimeTestGroup);
//ADD_TEST_GROUP(ModuleTestGroup);
ADD_TEST_GROUP(PinsTestGroup);
//ADD_TEST_GROUP(ButtonsTestGroup);

void SysTick_Handler(void)
{
	SystemTimer::getSystemTimer().updateTick();
}

void TIM3_IRQHandler()
{
	Timer::getTimer(moduleManagerTimerId)->update();
}

int main(void)
{
	MemAllocator::initAllocator(userHeapStart, userHeapSize);
	SystemTimer::getSystemTimer().setResolution(Microsecond(1000));

	auto testMgr = UTest::TestManager::getInstance();
	testMgr->runAllTests();
	testMgr->printResults();

	// Unfortunately print does not work in free version of TrueStudio
	// and vector does not support nice view of all its elements
	// so need to inspect each test's result in loop

	volatile bool loop = true;
	auto groups = testMgr->getTestGroups();
	auto tests = groups[0]->getTests();
	volatile auto res = UTest::TestBase::TestResult::Failed;

	for(auto test : tests)
	{
		res = test->getResult();
		if(res == UTest::TestBase::TestResult::Failed)
		{
			res = UTest::TestBase::TestResult::Failed;
		}
	}

	while(true)
	{
		if(loop == false)
			break;
	}

	return 0;
}
